tasks:
  - name: Prepare Gitpod environment
    before: |
      # Update settings.xml
      cp .mvn/gitpod-mvn-settings.xml ~/.m2/settings.xml
      cd $GITPOD_REPO_ROOT

      # sdkman auto answer
      sed -i 's/sdkman_auto_answer=false/sdkman_auto_answer=true/' $HOME/.sdkman/etc/config

      # SDKMAN
      sdk selfupdate
      sdk update
      sdk install maven 3.8.3
      sdk use maven 3.8.3

      # install gh
      brew install gh

vscode:
  extensions:
    - bierner.markdown-preview-github-styles
    - github.vscode-pull-request-github
    - redhat.fabric8-analytics
    - redhat.java
    - redhat.vscode-commons
    - redhat.vscode-xml
    - vscjava.vscode-maven
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-test
    - hbenl.test-adapter-converter
    - hbenl.vscode-test-explorer
